# Site Settings
encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]
lang: en # Language code as defined in _data/i18n.yml. en, en-gb, en-us, zh, zh-cn, zh-tw etc.
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
highlighter: rouge
markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://sallys.space # the base hostname & protocol for your site, e.g. http://example.com
baseurl: /blog # the subpath of your site, e.g. /blog
title: JuHyung Son
description: "sally's space"
keywords: 'jekyll, Machine Learning, Deep learning, blog'
author:
  name:
  job_title:
  location:
  email:
  social_links:
    - name: github
      url: https://github.com/jusonn
home:
  section1: <h1>JuHyung Son</h1>
  section2: <h2>Welcome!</h2>
  section3: <div class="social-links"><a class="ico-github btn" href="https://github.com/jusonn" title="View on GitHub"></a></div>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
  footer_content: juworld

disqus:
  shortname: jusonngit
  public_key: 6iyn3jyQGeFL638dtQOAbnuY3WVvvUgGQ10OF2txbqPXPus8rsm01RvyR8MiWI8J # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_analytics: 'UA-87765338-5' # e.g. 'UA-42456515-5'
addthis_public_id: ra-5abf64f599d0f323  # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
